# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='impuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=25)),
                ('precio', models.FloatField()),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orden.orden')),
            ],
        ),
        migrations.AddField(
            model_name='impuesto',
            name='id_orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orden.orden'),
        ),
    ]
